# Generated by Django 5.2.6 on 2025-09-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_roommembership_nickname_alter_roommembership_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
    ]
